// <auto-generated />
using System;
using DLL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace View.Migrations
{
    [DbContext(typeof(UkraineContext))]
    partial class UkraineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ChildrenSuitable")
                        .HasColumnType("bit");

                    b.Property<bool>("ContactlessDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("Delivery")
                        .HasColumnType("bit");

                    b.Property<bool>("DrivingService")
                        .HasColumnType("bit");

                    b.Property<bool>("FoodInRestaurant")
                        .HasColumnType("bit");

                    b.Property<bool>("FoodWithYou")
                        .HasColumnType("bit");

                    b.Property<bool>("FreeWiFi")
                        .HasColumnType("bit");

                    b.Property<bool>("SummerPlayground")
                        .HasColumnType("bit");

                    b.Property<bool>("Toilet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Built")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Domain.Models.Entertainment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("EntertainmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Entertainments");
                });

            modelBuilder.Entity("Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EntertainmentId")
                        .HasColumnType("int");

                    b.Property<int?>("MonumentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntertainmentId");

                    b.HasIndex("MonumentId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Domain.Models.Monument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("RegionId");

                    b.ToTable("Monuments");
                });

            modelBuilder.Entity("Domain.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Formed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 28131f,
                            Description = "The capital and largest city of Ukraine, one of the largest and oldest cities in Europe. Located in the middle reaches of the Dnieper, in the northern Dnieper region. Political, socio-economic, transport, educational, scientific, historical, cultural and spiritual center of Ukraine. In the system of administrative-territorial organization of Ukraine, Kyiv has a special status determined by the Constitution, and is not part of any region, although it is the administrative center of Kyiv region. Location of central authorities of Ukraine, foreign missions, headquarters of most enterprises and public associations operating in Ukraine.",
                            Formed = new DateTime(1932, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AA",
                            Name = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            Area = 28461f,
                            Description = "City in the south of Ukraine, the administrative center of the Kherson region. Located on the right high bank of the Dnieper. The population as of January 1, 2022 is 279,131 people. An important economic center of southern Ukraine. Significant railway junction (on the line Mykolaiv-Snihurivka-Dzhankoy), sea trade port, river port. Kherson has a satellite city Oleshka. Since July 17, 2020 it is the administrative center of Kherson district.",
                            Formed = new DateTime(1944, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BT",
                            Name = "Kherson"
                        },
                        new
                        {
                            Id = 3,
                            Area = 21831.97f,
                            Description = "Is an administrative-territorial unit in western Ukraine . It is one of the three regions of the historical and cultural region of Galicia (Eastern Lesser Poland), part of the Carpathian Euroregion . One of the most developed areas of the state in economic, tourist, cultural and scientific areas. It was formed on November 27, 1939 [ 2] after the annexation of the eastern part of Poland by the Soviet Union under the Molotov-Ribbentrop Pact .The Lviv region consists of 7 districts: Lviv , Drohobych , Chervonohrad , Stryj , Sambir , Zolochiv , and Yavoriv districts . Lviv region borders with Volyn , Rivne , Ternopil , Ivano-Frankivsk and Zakarpattia regions, has access to the state border with the Republic of Poland .The north of the region belongs to the zone of mixed forests, in particular, Maly Polissya ; the middle part - to the forest-steppe , where the ridges of Roztocze , Hologir , Voronyak , Opillya and the extreme western part of the Podil Upland stand out . Further south are the Carpathian foothills and, in fact, the Carpathians . They are represented by the Beskids . The southern border of the region coincides with the Verkhovyna Watershed . The territory of the region is also the main European watershed of the Black and Baltic Seas. The southern part of the Lviv-Volyn coal basin and the western parts of the Pre - Carpathian oil and gas region and the Pre - Carpathian sulfur - bearing basin are located in the Lviv region . The largest industrial centers are Chervonohrad , Lviv and Boryslav-Drohobych - Stebnytsia. Truskavets , Morshyn and Skhidnytsia are balneological resorts of international importance. Architectural ensembles of Lviv and Zhovkva , castles and other attractions, which are rich in the region, the Carpathian Mountains give great prospects for tourism development of the region.",
                            Formed = new DateTime(1939, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BC",
                            Name = "Lviv"
                        },
                        new
                        {
                            Id = 4,
                            Area = 8097f,
                            Description = "Region in the south-western part of Ukraine. Formed on August 7, 1940 from the northern, mostly inhabited by Ukrainians, part of Bukovina and the neighboring part of Bessarabia (with Khotyn). It is located within the Carpathians, Precarpathians (Bukovynian Prykarpattia) and Pokutsko-Bessarabian Upland.",
                            Formed = new DateTime(1940, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "CE",
                            Name = "Chernivtsi"
                        },
                        new
                        {
                            Id = 5,
                            Area = 28748f,
                            Description = "Administrative-territorial unit of Ukraine with the center in the city of Poltava. Formed on September 22, 1937. Located in the middle part of the Left Bank of Ukraine and, in part, on the Right Bank of Ukraine. Most of the region lies within the Dnieper lowland and Poltava plain.",
                            Formed = new DateTime(1937, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BI",
                            Name = "Poltava"
                        },
                        new
                        {
                            Id = 6,
                            Area = 24598f,
                            Description = "Region in Ukraine. Formed on September 22, 1937. Located in the south of the Black Sea lowlands in the lower reaches of the Southern Bug River. In the west it borders with Odessa, in the north with Kirovograd, in the east and northeast with Dnepropetrovsk and in the southeast with Kherson regions. In the south it is washed by the waters of the Black Sea. Area - 24.6 thousand km. The center of the region is the city of Mykolayiv.",
                            Formed = new DateTime(1937, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BE",
                            Name = "Mykolaiv"
                        },
                        new
                        {
                            Id = 7,
                            Area = 20629f,
                            Description = "Region in the west of Ukraine. It was founded on September 22, 1937 by a resolution of the CEC of the USSR with its center in the city of Kamianets-Podilskyi.",
                            Formed = new DateTime(1937, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BX",
                            Name = "Khmelnytsky"
                        },
                        new
                        {
                            Id = 8,
                            Area = 13823f,
                            Description = "Administrative-territorial unit of Ukraine with the center in the city of Ternopil. Located on the Podil Upland, the southern border of the region runs along the Dniester River, the eastern - on Zbruch. It occupies the eastern part of Galicia, part of southern Volhynia and part of Western Podillya.",
                            Formed = new DateTime(1939, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BO",
                            Name = "Ternopil"
                        },
                        new
                        {
                            Id = 9,
                            Area = 29832f,
                            Description = "Region in the north of Ukraine, within the Polissya lowland, in the south within the Dnieper upland. It borders the Gomel region of Belarus in the north, Kyiv in the east, Vinnytsia in the south, and Khmelnytsky and Rivne regions of Ukraine in the west. The administrative center is Zhytomyr. Created on September 22, 1937 from the western districts of Kyiv region.",
                            Formed = new DateTime(1937, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AM",
                            Name = "Zhytomyr"
                        },
                        new
                        {
                            Id = 10,
                            Area = 13928f,
                            Description = "Administrative-territorial unit in the west of Ukraine. It is one of the three regions of the historical and cultural region of Galicia.",
                            Formed = new DateTime(1939, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AT",
                            Name = "Ivano-Frankivsk"
                        },
                        new
                        {
                            Id = 11,
                            Area = 31865f,
                            Description = "Region in the north-eastern part of Ukraine. It borders on the west with Kyiv, on the north - with the Gomel region of the Republic of Belarus and the Bryansk region of the Russian Federation, on the east - with Sumy, on the south - with Poltava regions of Ukraine.",
                            Formed = new DateTime(1932, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "CB",
                            Name = "Chernihiv"
                        },
                        new
                        {
                            Id = 12,
                            Area = 20143f,
                            Description = "Region in the north-west of Ukraine within the Polissya lowland (over 3/4 of the territory) and Volyn upland. It is bordered on the west by the Lublin Voivodeship of the Republic of Poland, on the north by the Brest Region of the Republic of Belarus, on the east by the Rivne Region, and on the south by the Lviv Region of Ukraine. A total of 395 kilometers of the state border runs within the region.",
                            Formed = new DateTime(1939, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AC",
                            Name = "Volyn"
                        },
                        new
                        {
                            Id = 13,
                            Area = 26517f,
                            Description = "Administrative-territorial unit of Ukraine. It was formed within the modern boundaries on June 3, 1938, when the Voroshilovgrad region was separated from it",
                            Formed = new DateTime(1932, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AH",
                            Name = "Donetsk"
                        },
                        new
                        {
                            Id = 14,
                            Area = 33310f,
                            Description = "The largest region of Ukraine, located in the southwest of the country. One of the most developed regions of the country in economic, tourist, cultural and scientific areas. In the north and east it borders (clockwise) with Vinnytsia, Kirovohrad and Mykolayiv regions, is washed by the Black Sea, in the south - with Romania, in the west - with Moldova. The region includes Snake Island.",
                            Formed = new DateTime(1932, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BH",
                            Name = "Odesa"
                        },
                        new
                        {
                            Id = 15,
                            Area = 26513f,
                            Description = "Vinnytsia region was formed on February 27, 1932, when the CEC of the USSR approved the resolution of the IV extraordinary session of the All-Ukrainian Central Executive Committee of February 9, 1932 on the establishment of five regions in Ukraine. As of November 2020, the population is 370.0 thousand people. The regional center is the city of Vinnytsia. Located on the right bank of the Dnieper within the Podolsk Upland.",
                            Formed = new DateTime(1932, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AB",
                            Name = "Vinnytsia"
                        },
                        new
                        {
                            Id = 16,
                            Area = 31914f,
                            Description = "Region in Ukraine. Located in the central-eastern part of the country.",
                            Formed = new DateTime(1932, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AE",
                            Name = "Dnipropetrovsk"
                        },
                        new
                        {
                            Id = 17,
                            Area = 23834f,
                            Description = "Region in the north-eastern part of Ukraine; covers parts of the Middle Russian Uplands and the Dnieper Lowland.",
                            Formed = new DateTime(1939, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BM",
                            Name = "Sumy"
                        },
                        new
                        {
                            Id = 18,
                            Area = 12777f,
                            Description = "Region in the south-west of Ukraine within the western part of the Ukrainian Carpathians and the Transcarpathian lowlands. In the north it borders with Lviv, in the east with Ivano-Frankivsk regions of Ukraine. In the south with Romania, in the southwest with Hungary, in the west with Slovakia, in the northwest with Poland. Regional center - Uzhgorod.",
                            Formed = new DateTime(1946, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AO",
                            Name = "Transcarpathian"
                        },
                        new
                        {
                            Id = 19,
                            Area = 20047f,
                            Description = "Region in Ukraine. Located in the northwest of the country.",
                            Formed = new DateTime(1939, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BK",
                            Name = "Rivne"
                        },
                        new
                        {
                            Id = 20,
                            Area = 31415f,
                            Description = "Region in Slobidska Ukraine within the Dnieper lowlands and the Middle Russian uplands.",
                            Formed = new DateTime(1932, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AX",
                            Name = "Kharkiv"
                        },
                        new
                        {
                            Id = 21,
                            Area = 24588f,
                            Description = "It is located between the Dnieper and Southern Bug rivers in the south of the Dnieper Upland. Almost the entire territory of the region (except for the village of Vlasivka) is located on the right bank of the Dnieper. It borders Cherkasy in the north, Poltava in the northeast, Dnipropetrovsk in the east and southeast, Mykolayiv and Odesa in the south, and Vinnytsia in the west. According to one version, the geographical center of Ukraine is located near Dobrovelychkivka.",
                            Formed = new DateTime(1939, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BA",
                            Name = "Kirovohrad"
                        },
                        new
                        {
                            Id = 22,
                            Area = 20900f,
                            Description = "Administrative-territorial unit of Ukraine of the first level, located in the central forest-steppe part of the country on both banks of the middle reaches of the Dnieper and the Southern Bug.",
                            Formed = new DateTime(1954, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "CA",
                            Name = "Cherkasy"
                        },
                        new
                        {
                            Id = 23,
                            Area = 27180f,
                            Description = "Administrative unit in the south of Ukraine. Located in the southeast of Ukraine, it occupies mainly the left-bank part of the lower reaches of the Dnieper River. Regional center - the city of Zaporozhye.",
                            Formed = new DateTime(1939, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AP",
                            Name = "Zaporizhzhia"
                        },
                        new
                        {
                            Id = 24,
                            Area = 26684f,
                            Description = "Administrative-territorial unit of Ukraine, located in the east of the country, mainly in the basin of the middle reaches of the Seversky Donets. It ranks sixth in population and tenth in area among the administrative-territorial units of the country. In the south-west and west it borders with Donetsk region, and in the north-west - with Kharkiv region.",
                            Formed = new DateTime(1938, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "BB",
                            Name = "Luhansk"
                        },
                        new
                        {
                            Id = 25,
                            Area = 27000f,
                            Description = "The peninsula on the northern coast of the Black Sea, from the northeast is bordered by the Sea of ​​Azov. Located in the south of Ukraine and covers the Autonomous Republic of Crimea, Sevastopol and partly the south of the Kherson region (north of the Arabat arrow); most of the peninsula (Crimea and Sevastopol) from the end of February 2014 was captured and occupied by Russian regular military units, and later temporarily annexed by the Russian Federation.",
                            Formed = new DateTime(1869, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identifier = "AK",
                            Name = "Crimea"
                        });
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EntertainmentId")
                        .HasColumnType("int");

                    b.Property<int>("IdentityUserId")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntertainmentId");

                    b.HasIndex("MonumentId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Models.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntertainmentId")
                        .HasColumnType("int");

                    b.Property<int?>("MonumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntertainmentId");

                    b.HasIndex("MonumentId");

                    b.ToTable("WorkTimes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasIndex("ImageId");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Domain.Models.Address", b =>
                {
                    b.HasOne("Domain.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Domain.Models.Entertainment", b =>
                {
                    b.HasOne("Domain.Models.About", "About")
                        .WithMany()
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Region", null)
                        .WithMany("Entertainment")
                        .HasForeignKey("RegionId");

                    b.HasOne("Domain.Models.User", null)
                        .WithMany("Entertainments")
                        .HasForeignKey("UserId");

                    b.Navigation("About");

                    b.Navigation("Address");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Domain.Models.Image", b =>
                {
                    b.HasOne("Domain.Models.Entertainment", null)
                        .WithMany("Images")
                        .HasForeignKey("EntertainmentId");

                    b.HasOne("Domain.Models.Monument", null)
                        .WithMany("Images")
                        .HasForeignKey("MonumentId");

                    b.HasOne("Domain.Models.Review", null)
                        .WithMany("Images")
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("Domain.Models.Monument", b =>
                {
                    b.HasOne("Domain.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Region", null)
                        .WithMany("Monument")
                        .HasForeignKey("RegionId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.HasOne("Domain.Models.Entertainment", "Entertainment")
                        .WithMany("Reviews")
                        .HasForeignKey("EntertainmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Monument", "Monument")
                        .WithMany("Reviews")
                        .HasForeignKey("MonumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entertainment");

                    b.Navigation("Monument");
                });

            modelBuilder.Entity("Domain.Models.WorkTime", b =>
                {
                    b.HasOne("Domain.Models.Entertainment", null)
                        .WithMany("WorkTime")
                        .HasForeignKey("EntertainmentId");

                    b.HasOne("Domain.Models.Monument", null)
                        .WithMany("WorkTime")
                        .HasForeignKey("MonumentId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.HasOne("Domain.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.Models.Entertainment", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("Domain.Models.Monument", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("Domain.Models.Region", b =>
                {
                    b.Navigation("Entertainment");

                    b.Navigation("Monument");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Entertainments");
                });
#pragma warning restore 612, 618
        }
    }
}
